# Generated by Django 4.1.4 on 2022-12-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-name']},
        ),
    ]
