# Generated by Django 4.1.4 on 2022-12-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_alter_community_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
