# Generated by Django 4.1.4 on 2023-01-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_remove_room_topic_delete_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={},
        ),
    ]
