# Generated by Django 4.1.4 on 2022-12-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='img/assets/avatar.svg', null=True, upload_to='Profile_pics'),
        ),
    ]
